### ISSUE TITLE
How to run poseidon in the docker image?

### ISSUE THREAD

**Issue by thudzj** [nitnelave/docker-ml#1]
I have made the docker image run in a docker container, but I can not found Poseidon in the image. Should I just download the source codes of Poseidon into docker and then compile them and run them? I am newbie to use docker, so I hope there are someone who can help me. Thank you!

**Comment by nitnelave** [comment]
In the container, the source (built) is in `/poseidon`. You can start the training from inside one of the containers by providing a hosts file, or you can start the training from outside if you modify the startup script so it has the right paths.

**Comment by thudzj** [comment]
Thank you for your help. But, in fact, I cannot find /poseidon in the docker. I have got in the container by ssh and tried the comand "find / -name poseidon", but it returned nothing.

**Comment by nitnelave** [comment]
oh, right, indeed. I must have messed up the DockerFile. Let me fix that.

**Comment by thudzj** [comment]
OK. After you fix that, please let me know where to get the new DockerFile. Thank you very much!!!

**Comment by nitnelave** [comment]
The new, fixed Dockerfile is available on my github, in the same place. It should work. If it doesn't, tell me and I'll have a look on Monday.

Have fun!
