### ISSUE TITLE
fyi - osx is not supported for cuda + docker (style-transfer)

### ISSUE THREAD

**Issue by johndpope** [nitnelave/docker-ml#2]
Awesome job putting this together
I thought I'd highlight this caveat for others trying to get style-transfer to build. 
https://github.com/NVIDIA/nvidia-docker/issues/101

**Comment by nitnelave** [comment]
Thanks for the comment! Nothing I can really do about it, though. :/

**Comment by johndpope** [comment]
Did you actually get the style-transfer sample to run? re reading the NVIDIA/nvidia-docker#101 ticket - even if I go out and buy a new system - it won't work with docker.

**Comment by nitnelave** [comment]
Yes, I was able to run the style transfer, on a linux (CentOS) distribution.
